use_frameworks!

target 'paybear-ios_Example' do
  pod 'paybear-ios', :path => '../'

  target 'paybear-ios_Tests' do
    inherit! :search_paths
    pod 'paybear-ios', :path => '../'
    pod 'Quick'
    pod 'Nimble'
  end
end
